CREATE TABLE "TB_CLIENTES" (
  "ID" INTEGER NOT NULL,
  "NOMES_CLI" TEXT NOT NULL,
  PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "TB_VENDEDORES" (
  "ID" INTEGER NOT NULL,
  "NOME_VEND" TEXT NOT NULL,
  PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "TB_NOTASFISCAIS"(
  "ID" INTEGER NOT NULL,
  "NUM_NF" INTEGER NOT NULL,
  "SERIE_NF" INTEGER NOT NULL,
  "CLI_ID" INTEGER NOT NULL,
  "VEND_ID" INTEGER NOT NULL,
  PRIMARY KEY("ID" AUTOINCREMENT),
  FOREIGN KEY ("CLI_ID") REFERENCES "TB_CLIENTES"("ID"),
  FOREIGN KEY ("VEND_ID") REFERENCES "TB_VENDEDORES"("ID")
);

CREATE TABLE "TB_PRODUTOS"(
  "ID" INTEGER NOT NULL,
  "PRECO_UNIT" INTEGER NOT NULL,
  "NOME_PROD" TEXT NOT NULL,
  PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "TB_ITENS_NOTAFISCAL"(
  "ID" INTEGER NOT NULL,
  "NF_ID" INTEGER NOT NULL,
  "PRO_ID" INTEGER NOT NULL,
  "QTD" DOUBLE NOT NULL,
  "VALOR" DOUBLE NOT NULL,
  PRIMARY KEY("ID" AUTOINCREMENT),
  FOREIGN KEY ("NF_ID") REFERENCES "TB_NOTASFISCAIS"("ID"),
  FOREIGN KEY ("PRO_ID") REFERENCES "TB_PRODUTOS"("ID")
);

